### ISSUE TITLE
we need a secure way to share secrets

### ISSUE THREAD

**Issue by rsalmond** [gpo/gpo-platform-configs#30]
While continuing to refactor I'm going to need to be able to use the Github and Cloudflare APIs. I see some sensitive values have variable definitions. I'm guessing these are passed on the command line or env vars.

If so then the simplest thing to do might be to use [sops](https://getsops.io/docs/] to commit an encrypted `.env` file to this repo. Sops supports using a key stored in AWS KMS to encrypt files which solves the bootstrapping problem. We've already both got secure access to AWS.

If you're up for this @IanEdington I can cut a feature branch and get sops initialized, then you could populate it.

**Comment by IanEdington** [comment]
Absolutely! Let me know what I have to do
